name: Build and publish image, minimum (non-)working example

on:
  workflow_dispatch:

jobs:

  build-push-and-attest:
    name: Publish and attest
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: cstm-docs
      VERSION_TAG: ghcr.io/samsrabin/test-ctsm-docs-version-tagging/ctsm-docs:v1.0.2
      CONTAINER_PATH: doc/ctsm-docs_container

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2

      - name: Push Docker image
        id: push
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4
        with:
          context: ${{ env.CONTAINER_PATH }}
          platforms: linux/amd64,linux/arm64
          push: true
          load: false
          tags: ${{ env.VERSION_TAG }}
          labels: ""

